/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CategoryModal: typeof import('./src/components/settings/CategoryModal.vue')['default']
    CategorySelector: typeof import('./src/components/CategorySelector.vue')['default']
    Confirm: typeof import('./src/components/Confirm.vue')['default']
    EventModal: typeof import('./src/components/EventModal.vue')['default']
    GoalModal: typeof import('./src/components/settings/GoalModal.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    IconModal: typeof import('./src/components/IconModal.vue')['default']
    IGameIconsProgression: typeof import('~icons/game-icons/progression')['default']
    IPhArrowDownRightBold: typeof import('~icons/ph/arrow-down-right-bold')['default']
    IPhArrowUpRightBold: typeof import('~icons/ph/arrow-up-right-bold')['default']
    IPhBarbellLight: typeof import('~icons/ph/barbell-light')['default']
    IPhCheckCircleFill: typeof import('~icons/ph/check-circle-fill')['default']
    IPhCheckLight: typeof import('~icons/ph/check-light')['default']
    IPhCircleFill: typeof import('~icons/ph/circle-fill')['default']
    IPhCoffeeLight: typeof import('~icons/ph/coffee-light')['default']
    IPhDesktopLight: typeof import('~icons/ph/desktop-light')['default']
    IPhDotsThreeOutlineFill: typeof import('~icons/ph/dots-three-outline-fill')['default']
    IPhEyeLight: typeof import('~icons/ph/eye-light')['default']
    IPhFlagBanner: typeof import('~icons/ph/flag-banner')['default']
    IPhFolders: typeof import('~icons/ph/folders')['default']
    IPhGearFineLight: typeof import('~icons/ph/gear-fine-light')['default']
    IPhInfo: typeof import('~icons/ph/info')['default']
    IPhInfoLight: typeof import('~icons/ph/info-light')['default']
    IPhKey: typeof import('~icons/ph/key')['default']
    IPhMoonLight: typeof import('~icons/ph/moon-light')['default']
    IPhPaletteLight: typeof import('~icons/ph/palette-light')['default']
    IPhPencilSimpleLineLight: typeof import('~icons/ph/pencil-simple-line-light')['default']
    IPhPlusLight: typeof import('~icons/ph/plus-light')['default']
    IPhQuestionLight: typeof import('~icons/ph/question-light')['default']
    IPhSignOutLight: typeof import('~icons/ph/sign-out-light')['default']
    IPhSunLight: typeof import('~icons/ph/sun-light')['default']
    IPhTrashLight: typeof import('~icons/ph/trash-light')['default']
    IPhTrophyBold: typeof import('~icons/ph/trophy-bold')['default']
    IPhWarningLight: typeof import('~icons/ph/warning-light')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeModal: typeof import('./src/components/ThemeModal.vue')['default']
  }
}
